# Generated by Django 3.0.3 on 2020-02-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc_detail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img_main',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='img_thumb',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='alergy',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='begin_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='end_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition1',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition2',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition3',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition4',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition5',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='nutrition6',
            field=models.DecimalField(decimal_places=1, max_digits=4, null=True),
        ),
    ]
