# Generated by Django 3.0.3 on 2020-02-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200218_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='sizeinfo',
            table='sizeinfoes',
        ),
    ]
